### ISSUE TITLE
Rien ne se passe

### ISSUE THREAD

**Issue by guigui91** [pibooth/pibooth-extra-lights#1]
Bonjour j'ai brancher un relai srd-05vdc-sl-c . Je pensais qu'en installant ce plugin et elle reliant au pin 33 lors de la prise de photo la lumiere s'allumerait mais cela ne focntionne pas. J'ai bien rajouter la ligne dans le fichier de conf. Y'a t'il autre chose a faire?

merci

**Comment by guigui91** [comment]
autant pour moi c'est bon

**Comment by anxuae** [comment]
Hello @guigui91, does it mean that issue is solved?
