### ISSUE TITLE
Use more than 1 GPIO 

### ISSUE THREAD

**Issue by DJ-Dingo** [pibooth/pibooth-extra-lights#2]
use more than 1 GPIO per light
I have a relay, and i want LED with external power to. It works fine on my breadboard, but not in my circuit board.
Would it be possible to have GPIO, like flash_led_pin = (7, 15) or something, to run 2 GPIO on the same funktion

**Comment by anxuae** [comment]
@DJ-Dingo 

It could be a good improvement. The 2 pins (or more) will be driven at the same time UP and DOWN.
