### ISSUE TITLE
[enhancement] Add Time variable to flash

### ISSUE THREAD

**Issue by tutur05** [pibooth/pibooth-extra-lights#3]
Hi,
First, thanks you so much for you're Job ! This plugin is very usefull for using pibooth indoor !
I have a little problem in my case ! 
My conf is Pi 4 &Canon PowerShoot G10 

The problem is the flash stay on 5 seconds (I suppose it's time need G10 camera for switch to  preview mode at photo mode)
The little problem is the people don't now when smile and flash burn eyes... 
Can we add variable delay before start flash and how much time stay on ?
I now it's not usual solution but I suppose that all camera it's different so it's can be a easy solution for developper ?

Thanks you
tutur19

**Comment by werdeil** [comment]
Hi @tutur05 as you said, the 5 second is the time for your camera to take the photo.

As the application is in Python it is mono thread: first start the flash, then take the photo then stop the flash. There is no simple way to tell "start in x seconds" and in parallel take the photo.

I don't see a simple solution for this, the only thing I can think of is to handle the delay with hardware between the GPIO output and the flash.

But in fact the main issue is that I take 5s to shoot a photo, that was the main reason we switch on our main version of pibooth  to an hybrid mode (preview with a picamera and shoot with a DSLR).

**Comment by tutur05** [comment]
Hi @werdeil , 
thanks for answer. I was afraid you would say that. So, I start to build a adapter whit a attiny85 and potentiometer for set second delay. I publish my code when it's finish.
Have a nice day :)

**Comment by anxuae** [comment]
Hi @tutur05 , I propose to close this issue as you will solve it using electronic adapter.
Anyway, feel free to share your code and your solution here.

**Comment by tutur05** [comment]
Hi, 
not extraordinary , but for 6$, I  use Arduino Pro Mini and potentiometer 10K. A attiny can work too. You can use the potentiometer for set between 0 and 3000ms. Change coef if you need more.
Thanks to all :) 

```
int sensorPin = A0;    // Potentiometer 10K 
int flashPin = 3;      // = Pin 3 numeric
int readPin = 5; // Signal from raspberry
int sensorValue = 0;  // variable to store the value coming from the sensor
int i = 0;
void setup() {
  // declare the ledPin as an OUTPUT:
  pinMode(flashPin, OUTPUT);
  pinMode(readPin, INPUT);
  pinMode(13,OUTPUT);
  Serial.begin(9600);
}

void loop() {
  // read the value from the sensor:
if(digitalRead(readPin) == HIGH)
{
  Serial.print("Flash detecte / Poten ");
    sensorValue = analogRead(sensorPin);
    Serial.println(sensorValue);
    // Conversion pour 0/1023 => 1000/3000ms
    sensorValue = sensorValue*3;
    i = 0;
      while (i < sensorValue)
      {
      i = i + 100;
      Serial.println(i);
      delay(100);
      }
      
digitalWrite(flashPin, HIGH);
digitalWrite(13, HIGH);
delay(1000);
digitalWrite(flashPin,LOW);
digitalWrite(13, LOW);
Serial.println("Flash eteint");
delay(5000);
}
```
