### ISSUE TITLE
Preview LED always ON

### ISSUE THREAD

**Issue by hme0354** [pibooth/pibooth-extra-lights#5]
After starting pibooth Preview LED is always on. looks like same function of startup LED

**Comment by anxuae** [comment]
Hi @hme0354 ,

Can you give me logs files? The status will be forced to off at startup

**Comment by hme0354** [comment]
where do I find the logs?

**Comment by anxuae** [comment]
Hi @hme0354 , can you try the v1.0.2 of the plugin? The preview LED is forced to OFF at statup
